CREATE TABLE IF NOT EXISTS teacher (
id SERIAL NOT NULL,
name VARCHAR(25) NOT NULL,
age INT NOT NULL,

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS teacher_details (
id SERIAL NOT NULL,
subject VARCHAR(25) NOT NULL,
email VARCHAR(25) NOT NULL,
school_number INT NOT NULL,
teacher_id INT NOT NULL,

PRIMARY KEY(id),

CONSTRAINT FK_TEACHER_ID
FOREIGN KEY (teacher_id)
REFERENCES teacher (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);